### ISSUE TITLE
a question in the "wasserstein_bures_kernel" loss

### ISSUE THREAD

**Issue by lutongyv** [hannesdm/The-Bures-Metric-for-Generative-Adversarial-Networks#1]
K11 = fake_phi @ tf.transpose(fake_phi)
    K11 = K11 + epsilon * tf.eye(batch_size, dtype=dtype)
    K22 = real_phi @ tf.transpose(real_phi)
    K22 = K22 + epsilon * tf.eye(batch_size, dtype=dtype)

Hello :), recently I am trying to use the bures kernel loss which mentioned in your paper in my research, but I am confused about the useage of "epsilon * tf.eye(batch_size, dtype=dtype)" in your code, I suppose this is used to prevent the matrix from being invertible, or it could be used for something else?

**Comment by hannesdm** [comment]
The epsilon is to prevent numerical instabilities and make sure the matrices are PSD.
Note that we don't require any matrix inversions but the idea of why you would add an eps is similar.
